#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: wil-app
#  labels:
#    app: wil-app
#spec:
#  destination:
#    namespace: dev
#    server: 'https://kubernetes.default.svc'
#  source:
#    path: helm
#    repoURL: 'https://github.com/iltafah/iot-test.git'
#    targetRevision: HEAD
#    helm:
#      valueFiles:
#        - values.yaml
#  project: development
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/iltafah/iot-test.git'
    targetRevision: HEAD
    path: wil-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
